
ingress:
  fullnameOverride: openwallet-ingress-controller
  enabled: true
  className: gce
  staticIP: open-wallet-ip
  host: openwallet2025.com
  frontend:
    serviceName: front-server
    servicePort: 80
  backend:
    serviceName: backend-server
    servicePort: 8080