{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openwallet-backend.fullname" . }}
  namespace: openwallet
  labels:
{{- include "openwallet-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}  
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
{{- include "openwallet-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "openwallet-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}

          # (애플리케이션 컨텍스트 로딩 확인)
          startupProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: {{ .Values.backend.port }}
            failureThreshold: 30
            periodSeconds: 10

          # (Deadlock 등 내부 상태 확인)
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 15

          # (DB 연결 등 외부 의존성 체크 포함)
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10

          # 2. 환경 변수
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.dbUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.backend.env.dbUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.backend.env.dbPassword | quote }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.backend.contextPath }}
          # ai 서버 연결을 위한 ai 서버의 서비스 도메인:port 주소 지정
            - name: AI_SERVER_URL 
            value: "http://ai-service:8081"
          # 3. 리소스 설정
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}