frontend:
  fullnameOverride: openwallet-frontend-server
  enabled: true

  # Deployment 설정
  image:
    repository: ghcr.io/openwallet-2025/frontend
  tag: ""
    pullPolicy: Always
  replicaCount: 3
  port: 80

  # NGINX configMap 설정
  configMapName: openwallet-front-config
  configFile: default.conf

  # Service 설정
  service:
    name: front-server
    port: 80
    targetPort: 80

  



