backend:
  fullnameOverride: openwallet-backend-server
  enabled: true
  # Deployment 설정
  image:
    repository: ghcr.io/openwallet-2025/backend
    tag: "61c9242c2fa6f93dd63f6c46707ce3cd354e1ebc"
    pullPolicy: Always
  replicaCount: 1
  port: 8080
  contextPath: "/api"
  env:
    dbUrl: "jdbc:mysql://10.123.144.3:3306/openwallet-db?useSSL=false&allowPublicKeyRetrieval=true"
    dbUsername: "openwallet"
    dbPassword: "openwallet1234"
  # Service 설정
  service:
    name: backend-server
    port: 8080
    targetPort: 8080
  serviceAccountName: openwallet-ksa
  resources:
    requests:
      memory: "512Mi" # 최소 보장
      cpu: "250m"
    limits:
      memory: "1Gi" # 넘으면 강제 종료 (OOMKilled)
      cpu: "500m"
