apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwallet-main
spec:
  project: openwallet
  destination:
    server: https://kubernetes.default.svc
    namespace: openwallet
  source:
    repoURL: https://github.com/OpenWallet-2025/openwallet-manifests
    path: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
