apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwallet-frontend
spec:
  project: openwallet
  destination:
    namespace: openwallet
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/OpenWallet-2025/openwallet-manifests
    path: services/frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
