apiVersion: v1
kind: ConfigMap
metadata:
  name: openwallet-front-config
  namespace: openwallet
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /static;
        # 호스트 이름 와일드 카드로 지정

      location ~* ^/js/.*\.(js)$ {
        expires off;
        add_header Cache-Control "public, must-revalidate";
        try_files $uri =404;
    }

       location ~* ^/css/.*\.(css)$ {
        expires off;
        add_header Cache-Control "public, must-revalidate";
        try_files $uri =404;
    }


    # 이미지 파일 
      location ~* ^/img/.*\.(jpg|jpeg|png|gif|svg|ico|webp)$ {
          expires off;
          add_header Cache-Control "public";
          try_files $uri =404;
    }

      location / {

        index index.html;

        add_header Cache-Control "no-cache, no-store, must-revalidate";

        # 저장되지 않고(no-store), 만약 저장되더라도 사용하기 전에 
        # 무조건 서버에 최신 상태를 물어봐야 하며(no-cache), 
        # 서버와 연결할 수 없을 때는 사용하지 않도록(must-revalidate) 함 -> HTML 파일은 항상 최신 상태를 유지하도록 캐시 비활성화

        # /로 요청하면 $uri는 /static/에 index.html을 찾음
        #/<name.html>로 요청하면 /static/에 해당하는 파일을 찾음
        # 두 경우에서 파일을 찾지 못하면 404 에러를 반환합니다.

        try_files $uri $uri/ =404;
    }



        # 💡  server 블록의 닫는 중괄호
    }