apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server-deployment
  labels:
    app: front-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
      - name: nginx
        image: jaejeong999/nginx-front:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # 💡  ports 리스트를 정확히 정의
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      # 💡  'containers' 리스트 종료 후, 'volumes'는 'spec'과 같은 레벨로 이동
      volumes:
      - name: nginx-config-volume
        configMap:
          name: openwallet-front-config
          items:
          - key: default.conf
            path: default.conf