ai:
  fullnameOverride: openwallet-ai-server
  enabled: true
  image:
    repository: ghcr.io/openwallet-2025/ai
    tag: 0ba1e35
    pullPolicy: Always
  replicaCount: 1
  port: 8000
  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 20
    failureThreshold: 30
  startupProbe:
    httpGet:
      path: /health
      port: 8000
    failureThreshold: 30
    periodSeconds: 10
  env:
    dbUrl: jdbc:mysql://10.123.144.3:3306/openwallet-db?useSSL=false&allowPublicKeyRetrieval=true
    dbUsername: openwallet
    dbPassword: openwallet1234
  proxy:
    name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
    args:
      - '--private-ip'
      - my-project:asia-northeast3:openwallet-db
      - '--port=3306'
  runAsNonRoot: true
  resources:
    requests:
      cpu: '2'
      memory: 16Gi
      ephemeral-storage: 5Gi
    limits:
      cpu: '2'
      memory: 16Gi
      ephemeral-storage: 5Gi
  service:
    name: ai-server
    port: 8000
    targetPort: 8000
image:
  repository: ghcr.io/OpenWallet-2025/ai
  tag: a1e5419
