{{- if .Values.ai.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openwallet-ai.fullname" . }}
  namespace: openwallet
  labels:
{{- include "openwallet-ai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ai.replicaCount }}  
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
{{- include "openwallet-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "openwallet-ai.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ai-server
          image: "{{ .Values.ai.image.repository }}:{{ .Values.ai.image.tag }}"
          command: {{- .Values.ai.command}}
          args:
{{- toYaml .Values.ai.args | nindent 12 }}
          imagePullPolicy: {{ .Values.ai.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ai.port }}
          livenessProbe:
{{- toYaml .Values.ai.livenessProbe | nindent 12 }}
          startupProbe:
{{- toYaml .Values.ai.startupProbe | nindent 12 }}
         
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          
          volumeMounts:
            - name: google-cloud-key
              mountPath: "/var/secrets/google"
              readOnly: true
          

          resources:
              {{- toYaml .Values.ai.resources | nindent 12 }}
              
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
          args:
            - "--private-ip"
            - "my-project:asia-northeast3:openwallet-db"
            - "--port=3306"
          securityContext:
            runAsNonRoot: true
        

      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcp-auth-key
{{- end }}