{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server-deployment
  labels:
    app: openwallet-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: openwallet-frontend
  template:
    metadata:
      labels:
        app: openwallet-frontend
    spec:
      containers:
        - name: nginx
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/{{ .Values.frontend.configFile }}
              subPath: {{ .Values.frontend.configFile }}
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.frontend.configMapName }}
            items:
              - key: {{ .Values.frontend.configFile }}
                path: {{ .Values.frontend.configFile }}
{{- end }}
