{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: openwallet-frontend
spec:
  type: ClusterIP
  selector:
    app: openwallet-frontend   # Deployment와 동일해야 함
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
{{- end }}